matrix:
  include:
    - language: python
      python: "3.6.1"
      install:
      - pip install -r docker/requirements.txt
      script:
      - date
      - ls -al
      - coverage run --source=.. backend/tests.py
      - coverage report

    - language: node_js
      node_js: 
       - "stable"
      script:
      - npm run mocha-test --prefix=frontend
